### PR TITLE
dev/tasks/os_agnostic_tasks.yml: bump Go to 1.6

### PR DESCRIPTION
**Pull request by unclejack**
This bumps Go to 1.6.

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM

along with other optimizations go1.6 brings in some cool enhacements to text/templates that I have been waiting on for inventory file generation in cluster (https://talks.golang.org/2016/state-of-go.slide?utm_source=golangweekly&utm_medium=email#15)!

**Comment by mapuri** [comment]
@unclejack the sanity failed due to a collins download failure which appears intermittent atm. Can you please retrigger the sanity? otherwise this is good to merge.

**Comment by unclejack** [comment]
@mapuri The tests have passed on the CI. PTAL

**Comment by mapuri** [comment]
thanks @unclejack . LGTM

**Pull request merged**
