### PR TITLE
Remove auth proxy init step

### PR DESCRIPTION
**Pull request by neelimamukiri**
Init option was removed from auth_proxy as part of https://github.com/contiv/ccn/issues/191

### CODE REVIEW

**Review by yuva29 — COMMENTED** [review]
I suppose we need to change the `auth_proxy_image` along with these changes. https://github.com/contiv/ansible/blob/4d5e6ca5663809e3aefab88b1e004fb2abbfeee4/roles/auth_proxy/defaults/main.yml#L1

**Comment by neelimamukiri** [comment]
@yuva29, good point. Can you let me know what is the version to use that has the init cleanup?

**Comment by rhim** [comment]
A new version will have to be uploaded.



-Himanshu

On Feb 8, 2017, at 10:13 AM, neelimamukiri <notifications@github.com<mailto:notifications@github.com>> wrote:


@yuva29<https://github.com/yuva29>, good point. Can you let me know what is the version to use that has the init cleanup?

-

**Comment by rhim** [comment]
@yuva29, can you take care of this? Here are the steps:

1. Tag HEAD of master with 1.0.0-bata.2 and push it.
2. Build image contiv/auth_proxy:1.0.0-beta.2 and push to docker hub.

Ask for docker hub credentials from Neelima on slack.

Thanks,

-Himanshu

On Feb 8, 2017, at 10:13 AM, neelimamukiri <notifications@github.com<mailto:notifications@github.com>> wrote:


@yuva29<https://github.com/yuva29>, good point. Can you let me know what is the version to use that has the init cleanup?

-

**Comment by yuva29** [comment]
@rhim Yeah sure.

**Comment by yuva29** [comment]
Pushed https://hub.docker.com/r/contiv/auth_proxy/tags/

@neelimamukiri Please use the image with `1.0.0-beta.2` tag.

**Comment by neelimamukiri** [comment]
Thanks @yuva29. I updated the default tag.

**Review by yuva29 — APPROVED** [review]

**Review by rhim — APPROVED** [review]
LGTM.

**Pull request merged**
