### PR TITLE
Consul

### PR DESCRIPTION
**Pull request by erikh**
This is initial support for running consul on small clusters.

It is most certainly not intended to be a long-term solution. I will leave that to the experts. :D 

Please let me know if there's anything you'd like me to do with this patch.

### CODE REVIEW

**Comment by erikh** [comment]
cc @jainvipin

**Comment by mapuri** [comment]
thanks @erikh 

We need to add cleanup.yml that can take care care of stopping the service and cleaning up ip table rules. Otherwise LGTM !

**Comment by erikh** [comment]
@mapuri PTAL

**Comment by mapuri** [comment]
LGTM, thanks @erikh

**Pull request merged**
