### PR TITLE
stop docker service before starting the docker tcp socket unit

### LINKED ISSUE #26: Docker role fails on task "start docker tcp socket service".. Failure reason: docker-tcp.socket fails: Socket service docker.service already active
Docker role fails with the following message:
TASK: [docker | start docker tcp socket service] ******************************
failed: [node1] => {"failed": true}
msg: Job for docker-tcp.socket failed. See "systemctl status docker-tcp.socket" and "journalctl -xe" for details. 

contivuser@server:~$ sudo systemctl status -ln100 docker-tcp.socket
● docker-tcp.socket - Docker Socket for the API
   Loaded: loaded (/etc/systemd/system/docker-tcp.socket; disabled; vendor preset: enabled)
   Active: inactive (dead)
   Listen: [::]:2385 (Stream)

Jan 11 14:05:42 server systemd[1]: Socket service docker.service already active, refusing.
Jan 11 14:05:42 server systemd[1]: Failed to listen on Docker Socket for the API.
Jan 11 14:15:05 server systemd[1]: Socket service docker.service already active, refusing.
Jan 11 14:15:05 server systemd[1]: Failed to listen on Docker Socket for the API.

Seems to be the same issue as mentioned here: https://github.com/coreos/coreos-vagrant/issues/172
We could try to incorporate the solutions that have been suggested in the mentioned thread.

### PR DESCRIPTION
**Pull request by mapuri**
fixes #26

### CODE REVIEW

**Comment by erikh** [comment]
Can you check that it's not installed prior to restarting docker? This will break docker on re-provision.

**Comment by mapuri** [comment]
@erikh, ah, yes makes sense. I made this task conditional, see if it is better.

**Comment by erikh** [comment]
I don't know the changed syntax but I presume this works, so LGTM.

**Comment by mapuri** [comment]
Yep, I tested it locally here seems to work.

**Pull request merged**
