### PR TITLE
aws terraform script

### PR DESCRIPTION
**Pull request by dojacobs**
Terraform script that creates VMs on AWS for Contiv testing.

Removed AWS access & secret keys, plus other possibly sensitive entries.  These are specified in external aws.tfvars file - which will not be checked into Github.

Added documentation to the script for how to create tfvars file, and how to run the script.

### CODE REVIEW

**Comment by dojacobs** [comment]
@gaurav-dalvi - here's the aws script.  removed the access & secret keys.

**Comment by dojacobs** [comment]
@gaurav-dalvi  can you merge this when you get a chance?  thanks.

**Comment by dojacobs** [comment]
@unclejack - here's the PR for the aws script.  I'll do a separate PR for the vmware script.

**Comment by dseevr** [comment]
@dojacobs is this just the initial commit to get it into the repo?

Also I hope you revoked those access keys on AWS 😉

**Comment by dojacobs** [comment]
I revoked the old keys and created new ones. 

I have tested this script with my new keys.

**Review by dseevr — APPROVED** [review]

**Pull request merged**
