### PR TITLE
do not use sudo for local fetch ucp task

### PR DESCRIPTION
**Pull request by vvb**
- ansible has issues while mixing up local_action and root access.
- Fix for #79 
- For this fix itself to work we need ansible 2.0.

references: https://github.com/ansible/ansible/issues/10906

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM

**Comment by mapuri** [comment]
thinking more, may be we should add a task that checks/validates that the ansible control machine is running ansible v2.0. WDYT?

We can track that as a separate issue may be.

**Comment by vvb** [comment]
@mapuri yes, I will add the check.

**Comment by mapuri** [comment]
@vvb, is this ready for merge? 

Were you planning to add ansible version check as part of this? I have filed #87 to perform some checks, may be we can address it as part of that PR.

**Comment by vvb** [comment]
@mapuri that sounds better. so, this is good to merge then.

**Pull request merged**
