### PR TITLE
Adding golang role to ansible

### PR DESCRIPTION
**Pull request by gaurav-dalvi**
Signed-off-by: Gaurav Dalvi <gaurav1424@gmail.com>

### CODE REVIEW

**Comment by unclejack** [comment]
This can be found here https://github.com/contiv/ansible/blob/master/roles/dev/tasks/os_agnostic_tasks.yml already.

I don't agree, nor like to duplicate this code in two places. Why is this needed? We should use the existing code if it's needed for other roles than dev.

**Comment by gaurav-dalvi** [comment]
@unclejack : Good find. We need to have golang setup on one of the machines in our setup. We are trying to replicate our current vagrant approach. 

Someone send PR -- > Will trigger 3 VMs (e.g: swarm + contiv) then --> will compile code on node 1 and built binary and then start system-tests on that setup.

Current vagrant box has inbuilt golang installed in it.

**Comment by gaurav-dalvi** [comment]
I will try to hook this role into our installation yml.

**Comment by unclejack** [comment]
@gaurav-dalvi It's ok, I can make this change if you need it. I've got some other changes batched for ansible.

**Comment by unclejack** [comment]
I'm closing this in favor of issue #295.

**Pull request closed without merging**
