### PR TITLE
roles/docker: bump to Docker 1.11.0

### PR DESCRIPTION
**Pull request by unclejack**
This bumps Docker to 1.11.0.

### CODE REVIEW

**Comment by erikh** [comment]
This changes the default, which you can do in the Vagrantfile for netplugin specifically: https://github.com/contiv/volplugin/blob/master/Vagrantfile#L59

LGTM but you should be aware that changing this here changes it for everybody.

**Comment by unclejack** [comment]
@erikh The intention was to change it for everyone and include it in new boxes.

**Comment by mapuri** [comment]
@unclejack, just confirming that you are saying netplugin is fine with this docker version? If so we can merge this.

**Comment by erikh** [comment]
ah

**Comment by unclejack** [comment]
It seems this isn't OK for netplugin.

**Comment by mapuri** [comment]
@unclejack I will close this for now, let's resubmit once we have netplugin working with docker 1.11 . Let me know if you think otherwise.

**Pull request closed without merging**
