### PR TITLE
ansible: roll back etcd to 2.1.1

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM, just curious if you saw any stability issues with the new version of etcd or was it backward compatability?

**Comment by erikh** [comment]
Yeah it was melting

**Comment by erikh** [comment]
we'll have to look at it later when someone gets time to look at it.

**Comment by mapuri** [comment]
sure, cool. Can you retrigger the sanity? I will merge once it passes. I think this one failed on the ansible download task issue which is now merged.

**Pull request merged**
