### PR TITLE
Volplugin fixups

### PR DESCRIPTION
**Pull request by erikh**
This includes the LVM thin provisioning and updates to a recent version of netplugin. Sorry for the messy commits, but I'd really like to avoid squashing this (to avoid blowing my subtree up) if possible

### CODE REVIEW

**Comment by erikh** [comment]
what version of ansible is running here?

**Comment by mapuri** [comment]
this test host is running ansible1.9.4

**Comment by erikh** [comment]
can we get it on 2.0? no reason.. :)

**Comment by mapuri** [comment]
sure will do :), let me plan an upgrade of jenkins nodes sometime today

**Comment by mapuri** [comment]
@erikh the ansible is updated on all jenkins host, you may retrigger the sanity. This should be good to merge once sanity passes.

**Comment by erikh** [comment]
Preferring #118 to this patch, so closing this one

**Pull request closed without merging**
