### PR TITLE
update versions of contiv services, ucp and swarm

### PR DESCRIPTION
**Pull request by mapuri**

### CODE REVIEW

**Comment by vvb** [comment]
@mapuri may be we should also bump up docker_version to `1.10.3`

**Comment by mapuri** [comment]
yeah, the only issue is it doesn't work with Ubuntu. But I think you are right let me do that as well. I think net demo installer already set's docker version correctly based on OS type so we shall be fine there.

**Comment by erikh** [comment]
@vvb 1.11 was just released.

**Comment by mapuri** [comment]
ok, let me set it to 1.11

**Comment by mapuri** [comment]
@vvb brought up a good point that we may need to test 1.11 with our services before setting as a default. For now let me leave it as is. I think we are anyways setting desired version per project so this not urgent.

**Comment by erikh** [comment]
Makes complete sense, sorry to distract.

**Pull request merged**
