### PR TITLE
Nfs

### PR DESCRIPTION
**Pull request by erikh**
Here we go again...

New role: nfs. Role enabled in volplugin-test host group.

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM

**Comment by mapuri** [comment]
@erikh the commit history seems to be leaking in from volplugin. Is it possible to manually squash the commits in `nfs` ansible branch?

**Comment by erikh** [comment]
I think that's going to break in volplugin.

-Erik

**Comment by mapuri** [comment]
hmmm, this messes up ansible tree's history though.

I will merge this then but I think we should discuss (may be offline) about setting up a process for contributing changes to ansible, so that it keeps the master's history clean.

**Comment by erikh** [comment]
I agree, we need to have this harder to break.

**Comment by erikh** [comment]
Hey, it seems the extra commits were github, not git. Witness: https://github.com/contiv/ansible/commits/master

**Comment by erikh** [comment]
ah disregard, I see them now.

**Pull request merged**
