### PR TITLE
Ansible install

### PR DESCRIPTION
**Pull request by erikh**
This is the fix used in contiv/build to ensure ansible 2.0 is installed.

### CODE REVIEW

**Comment by mapuri** [comment]
thanks @erikh 

The commit history seems a bit out of place, may be because of subtree? Otherwise LGTM

**Comment by erikh** [comment]
yeah it got melded into another commit.. I think it'll be fine.

**Comment by mapuri** [comment]
ok, I will merge this once sanity passes.

**Comment by mapuri** [comment]
merging this, the cleanup sanity failed which will be fixed when #91 is merged

**Pull request merged**
