### PR TITLE
ansible/roles/base: ensure the latest ansible is installed.

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

### CODE REVIEW

**Comment by unclejack** [comment]
LGTM

**Comment by vvb** [comment]
LGTM

**Comment by mapuri** [comment]
@erikh LGTM

IIRC one concern with using the entire epel-testing repo was that it might bring in test/dev packages in prod.

I have fixed the ansible url issue in https://github.com/contiv/ansible/pull/104 but this fix is definitely better if using epel-testing here is ok.

**Comment by erikh** [comment]
Let's just go with this, it keeps things simpler. We can always move it 
back if there's a problem.

**Comment by mapuri** [comment]
SGTM

**Comment by unclejack** [comment]
We can install the packages which are dependencies for ansible before we install that package from testing and this would only bring in ansible from testing.

**Pull request merged**
