### PR TITLE
Bind

### PR DESCRIPTION
**Pull request by erikh**

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM

@erikh In the volplugin repo there was some discussion on using a different tool but it isn't closed yet. We can merge this whenever you are ready.

**Comment by dseevr** [comment]
I think dnsmasq is a better choice in general (far fewer CVEs... lol), but for what this is being used for, it doesn't really matter IMO

**Comment by erikh** [comment]
I agree with bill on literally everything here

this is dependent on @mapuri's merge into contiv/ansible which is why I'm waiting.

**Comment by erikh** [comment]
oh! this is contiv/ansible. ok. merging.

**Pull request merged**
