### PR TITLE
roles/etcd/tasks/main.yml: bump etcd to 2.2.5

### PR DESCRIPTION
**Pull request by unclejack**
This bumps etcd to the current stable release.

### CODE REVIEW

**Comment by mapuri** [comment]
etcd version update might need some testing and go ahead from netplugin and volplugin projects.

ping @shaleman @erikh to get their views.

**Comment by erikh** [comment]
WFM, I will test when I vendor in the latest.

**Comment by mapuri** [comment]
@unclejack, did you happen to verify netplugin sanities with this change?

I think we can merge this if netplugin is ok as well.

**Comment by unclejack** [comment]
@mapuri This works just fine with netplugin. I've tested with the current box and etcd 2.2.5.

**Comment by mapuri** [comment]
@unclejack thanks for verifying. LGTM

**Pull request merged**
