### PR TITLE
add dynamic loading to include modules

### PR DESCRIPTION
**Pull request by dvavili**
Add dynamic loading of include modules. The behavior of include modules changed in Ansible 2.1.
Include ignore_errors for ovs_cleanup tasks.

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
Thanks for taking care of this @DivyaVavili .
Do we need to do this change in all of the ansible repo, wherever we are using ignore_error ?
(all cleanup.ymls for each role ? )

**Comment by dvavili** [comment]
It's needed only for include modules. The ignore_errors directive in tasks will continue to function as before.

**Comment by gaurav-dalvi** [comment]
sorry I meant include modules. Do we need to modify at all places in this repo ?

**Comment by dvavili** [comment]
Lets not make this change everywhere. Dynamic loading seems to have different effects. If we hit other issues in which we see that the variables/directives are not getting inherited by included tasks, we will know what to fix.

**Comment by unclejack** [comment]
I've tested this and it seems to be OK.
LGTM

**Comment by gaurav-dalvi** [comment]
Tested this and it works !

**Pull request merged**
