### PR TITLE
adding aci_gw_image variable to ansible scripts

### PR DESCRIPTION
**Pull request by gaurav-dalvi**

### CODE REVIEW

**Comment by jojimt** [comment]
Please add a default value: contiv/aci-gw:latest
Other than that, LGTM

**Comment by gaurav-dalvi** [comment]
@jojimt : Default value is attached via this : 
https://github.com/contiv/demo/pull/98/files#diff-6a689c604ce54a47aab15671bd9c13acR152

**Comment by jojimt** [comment]
We still need a default in ansible (otherwise, ansible can only be run from net_demo_installer).

**Comment by gaurav-dalvi** [comment]
That wont work. I tested it. This is exactly similar change Reshma did it for contiv_network_version.
In that change we specified default value in net_demo_installer script and then we can overwrite by exporting shell variable. We dont have default value in ansible script though.

Reference : https://github.com/contiv/demo/pull/94

**Comment by jojimt** [comment]
@gaurav-dalvi the difference is that it is not possible to have a default value for contiv network version in ansible(there is not latest tag). In this case, it is possible to have a default and I think it is better to have it.

**Comment by gaurav-dalvi** [comment]
@jojimt : Updated the PR.

**Pull request closed without merging**
