### PR TITLE
ansible/roles/docker: use overlayfs storage backend.

### PR DESCRIPTION
**Pull request by erikh**
/cc @mapuri @unclejack @DivyaVavili this cut runtime for tests in half on volplugin.

Let's merge this ASAP.

### CODE REVIEW

**Comment by unclejack** [comment]
LGTM

**Comment by unclejack** [comment]
Won't we have problems on Ubuntu where we don't have a kernel with support for overlay? From what I know, Docker won't start if the requested graph driver can't be used.

**Comment by erikh** [comment]
ugh, really? what ubuntu are we on that's so ancient we can't?

**Comment by unclejack** [comment]
@erikh 15.04 has 3.16 or something along those lines by default. I'll have to test.

**Comment by erikh** [comment]
we install a 4.0 kernel as a part of the build repo at least. no idea what the other systems use.

**Comment by erikh** [comment]
@DivyaVavili can you verify this doesn't break your stuff?

**Comment by dvavili** [comment]
@erikh: Verified basic functionality with netplugin and launch/removal of containers and see no issues. Please go ahead.

**Pull request merged**
