### PR TITLE
Prepare for new CI

### PR DESCRIPTION
**Pull request by nbartos**

### CODE REVIEW

**Comment by neelimamukiri** [comment]
No test-test target being called, I'm assuming this is WIP. Also for Jenkins setups, do we want to test inside vagrant VMs?

**Comment by nbartos** [comment]
The intent of the initial cut is just to copy the relevant bits in contiv-jenkins.cisco.com, to make sure we can get those to pass before cleaning it up/making it more sane.

**Review by dseevr — APPROVED** [review]

**Comment by dseevr** [comment]
@neelimamukiri okay to merge?

**Review by unclejack — APPROVED** [review]
LGTM

**Pull request merged**
